apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  labels:
    app: aks-config-api # Label for the AKS configuration API
spec:
  accessModes:
    - ReadWriteOnce  # Allow single pod to mount volume for read/write
  resources:
    requests:
      storage: 1Gi  # Request minimum Azure Disk size
  storageClassName: managed-csi  # Use Azure Disk CSI driver (default)
  volumeMode: Filesystem  # Default mode