apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: aks-config-api
type: Opaque
stringData:
  # Store sensitive credentials as base64-encoded values
  secret-endpoint: "SecretEndpointValue"
  secret-access-key: "SecretAccessKey123456"
