apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: aks-config-api
type: Opaque
stringData:
  # Mock secrets - students will create these during the exercise
  secret-endpoint: "SecretEndpointValue"
  secret-access-key: "SecretAccessKey123456"
