id: /subscriptions/f96a9123-9b5a-4e58-aa99-4771f18a9a95/resourceGroups/rg-exercises/providers/Microsoft.App/containerapps/agent-api
identity:
  principalId: dd0352eb-d0ab-41b1-931e-2e455d10dcc3
  tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
  type: SystemAssigned
location: East US 2
name: agent-api
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: agent-api.icypond-4ce994b1.eastus2.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8080
      targetPortHttpScheme: null
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: null
    registries:
    - identity: system
      passwordSecretRef: ''
      server: acr42d29b3b.azurecr.io
      username: ''
    revisionTransitionThreshold: null
    runtime: null
    secrets: null
    service: null
    targetLabel: ''
  customDomainVerificationId: D12DEE2546E51F7632749E9DE271454680FCE32809C7724B5E5F80EF19DD9A93
  delegatedIdentities: []
  environmentId: /subscriptions/f96a9123-9b5a-4e58-aa99-4771f18a9a95/resourceGroups/rg-exercises/providers/Microsoft.App/managedEnvironments/aca-env-42d29b3b
  eventStreamEndpoint: https://eastus2.azurecontainerapps.dev/subscriptions/f96a9123-9b5a-4e58-aa99-4771f18a9a95/resourceGroups/rg-exercises/containerApps/agent-api/eventstream
  latestReadyRevisionName: agent-api--0000002
  latestRevisionFqdn: agent-api--0000002.icypond-4ce994b1.eastus2.azurecontainerapps.io
  latestRevisionName: agent-api--0000002
  managedEnvironmentId: /subscriptions/f96a9123-9b5a-4e58-aa99-4771f18a9a95/resourceGroups/rg-exercises/providers/Microsoft.App/managedEnvironments/aca-env-42d29b3b
  outboundIpAddresses:
  - 20.1.250.250
  - 20.1.251.135
  - 20.7.131.26
  - 20.7.130.240
  - 20.7.131.54
  - 20.7.131.60
  - 20.7.131.34
  - 20.7.131.59
  - 20.7.131.44
  - 20.7.131.5
  - 20.7.131.39
  - 20.7.131.50
  - 20.1.251.104
  - 172.200.51.234
  - 172.200.52.27
  - 172.200.51.44
  - 172.200.51.235
  - 172.200.51.243
  - 172.200.51.45
  - 172.200.51.191
  - 172.200.51.242
  - 172.200.52.26
  - 172.200.51.190
  - 20.1.251.2
  - 4.153.75.54
  - 172.193.97.218
  - 68.220.18.20
  - 172.193.72.214
  - 20.161.102.207
  - 130.213.148.50
  - 68.220.243.198
  - 13.68.118.203
  - 13.68.119.127
  - 52.184.147.35
  - 52.184.147.9
  - 20.94.111.32
  - 20.94.110.46
  - 130.213.251.138
  - 68.220.200.118
  - 172.175.128.181
  - 172.193.48.200
  - 68.220.140.24
  - 68.220.243.140
  - 20.161.90.45
  - 20.15.73.80
  - 172.193.33.53
  - 48.214.4.169
  - 20.97.130.219
  - 20.69.200.68
  - 52.167.135.54
  - 52.184.149.238
  - 52.179.250.88
  - 52.184.149.147
  - 52.184.198.180
  - 52.184.138.179
  - 52.179.253.112
  - 52.184.190.79
  - 52.184.141.185
  - 52.184.151.206
  - 20.97.132.38
  - 4.153.163.131
  - 20.36.242.179
  - 20.36.243.222
  - 20.36.243.227
  - 20.36.243.208
  - 128.85.230.186
  - 4.153.163.156
  - 20.36.242.169
  - 4.153.163.201
  - 20.36.244.19
  - 20.97.133.137
  - 20.36.244.21
  - 20.36.243.201
  - 128.85.220.176
  - 128.85.212.114
  - 135.18.214.171
  - 20.85.91.213
  - 128.85.239.223
  - 4.153.23.192
  - 4.153.23.210
  - 4.153.23.204
  - 20.94.122.99
  - 4.153.23.173
  - 20.94.122.65
  - 20.94.122.133
  - 20.94.122.111
  - 20.94.122.70
  - 20.94.122.101
  - 20.161.106.192
  patchingMode: Automatic
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: AGENT_DEFAULT_DELAY_MS
        value: '500'
      image: acr42d29b3b.azurecr.io/agent-api:v1
      imageType: ContainerImage
      name: agent-api
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    customMetricsSettings: null
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 200
      maxReplicas: 5
      minReplicas: 1
      pollingInterval: 30
      rules:
      - http:
          metadata:
            concurrentRequests: '10'
        name: http-scaling
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: Consumption
resourceGroup: rg-exercises
systemData:
  createdAt: '2026-01-24T17:25:29.3251616'
  createdBy: Jeff.Koch@microsoft.com
  createdByType: User
  lastModifiedAt: '2026-01-24T17:57:17.6659492'
  lastModifiedBy: Jeff.Koch@microsoft.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
