apiVersion: v1
kind: Service
metadata:
  name: aks-api-service
  labels:
    app: aks-api
spec:
  type: LoadBalancer
  selector:
    app: aks-api
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
